spring.application.name=rate-limiter
rate-limiter.token-bucket.capacity=20
rate-limiter.token-bucket.refill-rate-per-second=1
rate-limiter.leaky-bucket.capacity=20
rate-limiter.leaky-bucket.leak-rate-per-second=1